### ISSUE TITLE
Incorrect minification of ::before and ::after

### ISSUE THREAD

**Issue by slytael** [KK578/grunt-minify-polymer#1]
The minifyPolymerCSS grunt script, leaves a space after the ::after and ::before pseudo selectors. 

So for instance a rule of the form:
>div::after {}

will be minified to 
>div ::after {} 

which is a broken rule.

**Comment by KK578** [comment]
Hi, this should now be resolved in v2.0.1.

Can you update your project to this version and test if it now minifies correctly for you?
