### ISSUE TITLE
Parser error on encountering `

### ISSUE THREAD

**Issue by gerard-payne** [KK578/grunt-minify-polymer#4]
The `character causes an error. Found in bower installed highlightjs package.
 Error while minifying JS: Unexpected character '`' (line: 1, col: 0, pos: 0)

**Comment by KK578** [comment]
Hey, could you link the highlightjs package or give the bower command to install it please?

**Comment by KK578** [comment]
Updated UglifyJS so it should support these backticks '\`' now in v2.1.0.
Can you update grunt-minify-polymer and try again?

**Comment by gerard-payne** [comment]
thank you the error no longer appears
