### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by Compufreak345** [KK578/grunt-minify-polymer#5]
It seems like there is an issue pulling UglifyJS : 

> npm install -g grunt-minify-polymer
> npm ERR! git clone git@github.com:github:mishoo/UglifyJS2 Cloning into bare repository ...
> npm ERR! git clone git@github.com:github:mishoo/UglifyJS2 fatal: remote error:
> npm ERR! git clone git@github.com:github:mishoo/UglifyJS2    is not a valid repository name
> npm ERR! git clone git@github.com:github:mishoo/UglifyJS2   Email support@github.com for help
> npm ERR! notarget No compatible version found: uglify-js@'github:mishoo/UglifyJS2#harmony'

**Comment by KK578** [comment]
Hi, I can't reproduce this issue.
What version of node/npm are you using?

**Comment by Compufreak345** [comment]
Oh - I somehow had fixed npm to an old version in my buildfile... Updating npm fixed it, thanks & sorry for bothering you :>

**Comment by KK578** [comment]
Haha, no problem! :+1:
